# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
import os
import sys

import app.log
import app.regex

_todo = r"TODO\([\S@.]+\)"

__common_keywords = ["break", "continue", "else", "for", "if", "return", "while"]

__c_keywords = __common_keywords + [
    "case",
    "const",
    "default",
    "do",
    "enum",
    "goto",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
]

__linux_commands = [
    "ag",
    "basename",
    "bash",
    "cd",
    "chmod",
    "cp",
    "dircolors",
    "dirname",
    "echo",
    "egrep",
    "find",
    "grep",
    "inotify",
    "inotifywait",
    "ixoff",
    "ixon",
    "lesspipe",
    "ln",
    "ls",
    "mkdir",
    "read",
    "rm",
    "rmdir",
    "rxvt",
    "sed",
    "sh",
    "shell",
    "sleep",
    "ssh",
    "tput",
    "uname",
    "wc",
    "which",
    "xargs",
]

if sys.version_info[0] == 2:
    # The Python2 re limits the number of named groups. Reduce the keywords
    # recognized.
    __cpp_keywords = [
        "auto",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "constexpr",
        "continue",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "false",
        "for",
        "friend",
        "if",
        "inline",
        "mutable",
        "namespace",
        "new",
        "noexcept",
        "nullptr",
        "override",
        "private",
        "protected",
        "public",
        "return",
        "sizeof",
        "static",
        "struct",
        "switch",
        "template",
        "this",
        "throw",
        "true",
        "typedef",
        "typename",
        "virtual",
        "while",
    ]
    __c_primitive_types = [
        "bool",
        "char",
        "double",
        "float",
        "int",
        "int8_t",
        "int16_t",
        "int32_t",
        "int64_t",
        "int_max_t",
        "int8_t",
        "int16_t",
        "int32_t",
        "int64_t",
        "intptr_t",
        "ptrdiff_t",
        "size_t",
        "long",
        "signed",
        "short",
        "uint8_t",
        "uint16_t",
        "uint32_t",
        "uint_max_t",
        "uintptr_t",
        "unsigned",
        "void",
        "wchar_t",
    ]
else:
    __cpp_keywords = [
        "alignas",
        "alignof",
        "and",
        "and_eq",
        "asm",
        "audit",
        "auto",
        "axiom",
        "bitand",
        "bitor",
        "break",
        "case",
        "catch",
        "class",
        "compl",
        "concept",
        "const",
        "const_cast",
        "consteval",
        "constexpr",
        "continue",
        "decltype",
        "default",
        "delete",
        "do",
        "dynamic_cast",
        "else",
        "enum",
        "explicit",
        "export",
        "extern",
        "false",
        "final",
        "for",
        "friend",
        "goto",
        "if",
        "inline",
        "mutable",
        "namespace",
        "new",
        "noexcept",
        "not",
        "not_eq",
        "nullptr",
        "operator",
        "or",
        "or_eq",
        "override",
        "private",
        "protected",
        "public",
        "register",
        "reinterpret_cast",
        "return",
        "sizeof",
        "static",
        "static_assert",
        "static_cast",
        "struct",
        "switch",
        "template",
        "this",
        "thread_local",
        "throw",
        "true",
        "typedef",
        "typename",
        "virtual",
        "volatile",
        "while",
        "xor",
        "xor_eq",
    ]
    __c_primitive_types = [
        "bool",
        "char",
        "double",
        "float",
        "int",
        "int8_t",
        "int16_t",
        "int32_t",
        "int64_t",
        "int_fast8_t",
        "int_fast16_t",
        "int_fast32_t",
        "int_fast64_t",
        "int_least8_t",
        "int_least16_t",
        "int_least32_t",
        "int_least64_t",
        "int_max_t",
        "int8_t",
        "int16_t",
        "int32_t",
        "int64_t",
        "intptr_t",
        "ptrdiff_t",
        "size_t",
        "long",
        "signed",
        "short",
        "uint8_t",
        "uint16_t",
        "uint32_t",
        "uint64_t",
        "uint_fast8_t",
        "uint_fast16_t",
        "uint_fast32_t",
        "uint_fast64_t",
        "uint_least8_t",
        "uint_least16_t",
        "uint_least32_t",
        "uint_least64_t",
        "uint_max_t",
        "uintptr_t",
        "unsigned",
        "void",
        "wchar_t",
    ]

__chrome_extension = r"""\b[a-z]{32}\b"""
__sha_1 = r"""\b[a-z0-9]{40}\b"""

__special_string_escapes = [
    r"\\\\",
    r"\\b",
    r"\\f",
    r"\\n",
    r"\\r",
    r"\\t",
    r"\\v",
    r"\\0[0-7]{0,3}",
    __chrome_extension,
    __sha_1,
]

color8 = {
    "_pre_selection": 1,
    "bracket": 1,
    "c": 0,
    "c_path_bracketed_file": 3,
    "c_path_quoted_file": 3,
    "c_preprocessor": 1,
    "c_preprocessor_include": 1,
    "c_raw_string1": 3,
    "c_raw_string2": 3,
    "c_string1": 3,
    "c_string2": 3,
    "context_menu": 1,
    "context_menu_highlight": 1,
    "cpp_block_comment": 2,
    "cpp_line_comment": 2,
    "cpp_string_literal": 2,
    "current_line": 1,
    "dart_nesting_block_comment": 2,
    "debug_window": 1,
    "default": 0,
    "doc_block_comment": 3,
    "error": 7,
    "found_find": 1,
    "highlight": 3,
    "html_block_comment": 2,
    "html_element": 1,
    "html_element_end": 1,
    "js_string": 3,
    "keyword": 1,
    "line_number": 7,
    "line_number_current": 6,
    "line_overflow": 7,
    "logo": 7,
    "matching_bracket": 1,
    "matching_find": 1,
    "md_code": 2,
    "md_heading": 3,
    "md_link": 2,
    "message_line": 3,
    "misspelling": 3,
    "number": 1,
    "outside_document": 7,
    "popup_window": 0,
    "pound_comment": 3,
    "py_import": 1,
    "py_import_file": 2,
    "py_raw_string1": 2,
    "py_raw_string2": 2,
    "py_string1": 2,
    "py_string2": 2,
    "quoted_string2": 2,
    "regex_string": 2,
    "right_column": 6,
    "rs_block_comment": 2,
    "rs_byte_string1": 3,
    "rs_byte_string2": 3,
    "rs_label_or_char": 3,
    "rs_raw_string": 3,
    "selected": 5,
    "special": 1,
    "status_line": 7,
    "status_line_error": 7,
    "text": 0,
    "top_info": 7,
    "trailing_space": 1,
    "type": 1,
}

for i in color8.values():
    assert 0 <= i < 8, i

comment_color_16_index = 2
default_color_16_index = 1
found_color_16_index = 3
keywords_color_16_index = 2
path_color_16_index = 6
selected_color_16_index = 4  # Active find is a selection.
specials_color_16_index = 5
string_color_16_index = 6
outside_of_buffer_color_16_index = 7
border_color_16_index = 8
border_highlight_color_16_index = 9

color16 = {
    "_pre_selection": string_color_16_index,
    "bracket": 6,
    "c": default_color_16_index,
    "c_path_bracketed_file": path_color_16_index,
    "c_path_quoted_file": path_color_16_index,
    "c_preprocessor": 1,
    "c_preprocessor_include": specials_color_16_index,
    "c_raw_string1": string_color_16_index,
    "c_raw_string2": string_color_16_index,
    "c_string1": string_color_16_index,
    "c_string2": string_color_16_index,
    "context_menu": 15,
    "context_menu_highlight": 14,
    "cpp_block_comment": comment_color_16_index,
    "cpp_line_comment": comment_color_16_index,
    "cpp_string_literal": string_color_16_index,
    "current_line": 15,
    "dart_nesting_block_comment": comment_color_16_index,
    "debug_window": default_color_16_index,
    "default": default_color_16_index,
    "doc_block_comment": comment_color_16_index,
    "error": 9,
    "found_find": found_color_16_index,
    "highlight": 15,
    "html_block_comment": comment_color_16_index,
    "html_element": keywords_color_16_index,
    "html_element_end": keywords_color_16_index,
    "js_string": string_color_16_index,
    "keyword": keywords_color_16_index,
    "line_number": border_color_16_index,
    "line_number_current": border_highlight_color_16_index,
    "line_overflow": 15,
    "logo": border_color_16_index,
    "matching_bracket": 15,
    "matching_find": 9,
    "md_code": string_color_16_index,
    "md_heading": specials_color_16_index,
    "md_link": string_color_16_index,
    "message_line": border_color_16_index,
    "misspelling": 9,
    "number": 2,
    "outside_document": outside_of_buffer_color_16_index,
    "popup_window": border_color_16_index,
    "pound_comment": comment_color_16_index,
    "py_import": keywords_color_16_index,
    "py_import_file": string_color_16_index,
    "py_raw_string1": string_color_16_index,
    "py_raw_string2": string_color_16_index,
    "py_string1": string_color_16_index,
    "py_string2": string_color_16_index,
    "quoted_string2": string_color_16_index,
    "regex_string": string_color_16_index,
    "right_column": outside_of_buffer_color_16_index,
    "rs_block_comment": comment_color_16_index,
    "rs_byte_string1": string_color_16_index,
    "rs_byte_string2": string_color_16_index,
    "rs_label_or_char": string_color_16_index,
    "rs_raw_string": string_color_16_index,
    "selected": selected_color_16_index,
    "special": specials_color_16_index,
    "status_line": border_color_16_index,
    "status_line_error": border_highlight_color_16_index,
    "text": default_color_16_index,
    "top_info": border_color_16_index,
    "trailing_space": 15,
    "type": keywords_color_16_index,
}

for i in color16.values():
    assert 0 <= i < 16, i

comment_color_index = 2
default_color_index = 18
found_color_index = 32
keywords_color_index = 21
path_color_index = 30
selected_color = 64  # Active find is a selection.
specials_color_index = 20
string_color_index = 5
outside_of_buffer_color_index = 211

color256 = {
    "_pre_selection": string_color_index,
    "bracket": 6,
    "c": default_color_index,
    "c_path_bracketed_file": path_color_index,
    "c_path_quoted_file": path_color_index,
    "c_preprocessor": 1,
    "c_preprocessor_include": specials_color_index,
    "c_raw_string1": string_color_index,
    "c_raw_string2": string_color_index,
    "c_string1": string_color_index,
    "c_string2": string_color_index,
    "context_menu": 201,
    "context_menu_highlight": 200,
    "cpp_block_comment": comment_color_index,
    "cpp_line_comment": comment_color_index,
    "cpp_string_literal": string_color_index,
    "current_line": 180,
    "dart_nesting_block_comment": comment_color_index,
    "debug_window": default_color_index,
    "default": default_color_index,
    "doc_block_comment": comment_color_index,
    "error": 9,
    "found_find": found_color_index,
    "highlight": 96,
    "html_block_comment": comment_color_index,
    "html_element": keywords_color_index,
    "html_element_end": keywords_color_index,
    "js_string": string_color_index,
    "keyword": keywords_color_index,
    "line_number": 168,
    "line_number_current": 146,
    "line_overflow": 105,
    "logo": 168,
    "matching_bracket": 201,
    "matching_find": 9,
    "md_code": string_color_index,
    "md_heading": specials_color_index,
    "md_link": string_color_index,
    "message_line": 3,
    "misspelling": 9,
    "number": 31,
    "outside_document": outside_of_buffer_color_index,
    "popup_window": 117,
    "pound_comment": comment_color_index,
    "py_import": keywords_color_index,
    "py_import_file": string_color_index,
    "py_raw_string1": string_color_index,
    "py_raw_string2": string_color_index,
    "py_string1": string_color_index,
    "py_string2": string_color_index,
    "quoted_string2": string_color_index,
    "regex_string": string_color_index,
    "right_column": outside_of_buffer_color_index,
    "rs_block_comment": comment_color_index,
    "rs_byte_string1": string_color_index,
    "rs_byte_string2": string_color_index,
    "rs_label_or_char": string_color_index,
    "rs_raw_string": string_color_index,
    "selected": selected_color,
    "special": specials_color_index,
    "status_line": 168,
    "status_line_error": 161,
    "text": default_color_index,
    "top_info": 168,
    "trailing_space": 180,
    "type": keywords_color_index,
}

for i in color256.values():
    assert 0 <= i < 256, i

# Please keep these color dictionaries in sync.
assert color8.keys() == color256.keys()
assert color16.keys() == color256.keys()

# These prefs are not fully working.
prefs = {
    "color": {},
    "dev_test": {},
    # TODO(dschuyler): provide a UI to enable selected dictionaries.
    "dictionaries": {
        # The base dictionaries are loaded at startup. They are active for all
        # documents.
        "base": [
            "acronyms",
            "coding",
            "contractions",
            "cpp",
            "css",
            "en-abbreviations",
            "en-gb",
            "en-misc",
            "en-us",
            "html",
            "name",
            "user",
        ],
        # If the expanded path to the current document contains |key| the list
        # of dictionaries are applied.
        "path_match": {
            "/chromium/": ["chromium"],
            "/fuchsia/": ["fuchsia"],
        },
    },
    "editor": {
        # Whether to automatically indent after pressing carriage return.
        "auto_indent": True,
        # E.g. When key "(" is pressed, "()" is typed.
        "auto_insert_closing_character": False,
        # When opening a path that starts with "//", the value is used to
        # replace the first slash in a double slash prefix.
        "base_dir_env": "/",  # "${FUCHSIA_DIR}",
        # Scroll the window to keep the cursor on screen.
        "captive_cursor": False,
        "color_scheme": "default",
        # Show hidden files in file list.
        "files_show_dot_files": True,
        # Show the size on disk for files in the file list.
        "files_show_sizes": True,
        "files_show_modified_dates": True,
        "files_sort_ascending_by_name": True,
        "files_sort_ascending_by_size": None,
        "files_sort_ascending_by_modified_date": None,
        "find_dot_all": False,
        "find_ignore_case": True,
        "find_locale": False,
        "find_multi_line": False,
        "find_unicode": True,
        "find_use_regex": True,
        "find_verbose": False,
        "find_whole_word": False,
        # An example indentation. If the grammar has its own indent that can
        # override this value.
        "indentation": "  ",
        "line_limit_indicator": 80,
        # When the mouse wheel is moved, which way should the window scroll.
        "natural_scroll_direction": True,
        "on_save_strip_trailing_spaces": True,
        # Ratio of columns: 0 left, 1.0 right.
        "optimal_cursor_col": 0.98,
        # Ratio of rows: 0 top, 0.5 middle, 1.0 bottom.
        "optimal_cursor_row": 0.28,
        "palette": "default",
        "palette8": "default8",
        "palette16": "default16",
        "palette256": "default256",
        "prediction_show_open_files": True,
        "prediction_show_alternate_files": True,
        "prediction_show_recent_files": True,
        "prediction_sort_ascending_by_prediction": True,
        "prediction_sort_ascending_by_type": None,
        "prediction_sort_ascending_by_name": None,
        "prediction_sort_ascending_by_status": None,
        "save_undo": True,
        "show_line_numbers": True,
        "show_status_line": True,
        "show_top_info": True,
        # Convert/expand tabs to spaces (see tab_size).
        "tab_to_spaces": True,
        # When expanding tabs to spaces, how many spaces to use. This is not
        # used for indentation, see "indentation" or grammar "indent".
        "tab_size": 8,
        # Use a background thread to process changes and parse grammars.
        "useBgThread": True,
    },
    "file_type": {
        "bash": {
            "ext": [".bash", ".sh"],
            "grammar": "bash",
            "tab_to_spaces": True,
        },
        "bazel": {
            "ext": [],
            "grammar": "bazel",
            "name": ["BUILD"],
            "tab_to_spaces": True,
        },
        "binary": {
            "ext": [
                ".exe",
                ".gz",
                ".gzip",
                ".jar",
                ".jpg",
                ".jpeg",
                ".o",
                ".obj",
                ".png",
                ".pyc",
                ".pyo",
                ".tgz",
                ".tiff",
                ".zip",
            ],
            "grammar": "binary",
            "tab_to_spaces": False,
        },
        "c": {
            "ext": [".c"],
            "grammar": "c",
            "tab_to_spaces": True,
        },
        "cpp": {
            "ext": [
                ".cc",
                ".cpp",
                ".cxx",
                ".c++",
                ".hpp",
                ".hxx",
                ".h++",
                ".inc",
                ".h",  # Hmm, some source uses .h for cpp headers.
            ],
            "grammar": "cpp",
            "tab_to_spaces": True,
        },
        "css": {
            "ext": [".css", "_css.html"],
            "grammar": "css",
            "tab_to_spaces": True,
        },
        "dart": {
            "ext": [
                ".dart",
            ],
            "grammar": "dart",
            "tab_to_spaces": True,
        },
        "fidl": {
            "ext": [".fidl"],
            "grammar": "fidl",
            "tab_to_spaces": True,
        },
        "gn": {
            "ext": [".gn", ".gni"],
            "grammar": "gn",
            "tab_to_spaces": True,
        },
        "golang": {
            "ext": [
                ".go",
            ],
            "grammar": "golang",
            "tab_to_spaces": True,
        },
        "grd": {
            "ext": [".grd", ".grdp"],
            "grammar": "grd",
            "tab_to_spaces": True,
        },
        "html": {
            "ext": [".htm", ".html"],
            "grammar": "html",
            "tab_to_spaces": True,
        },
        "java": {
            "ext": [
                ".java",
            ],
            "grammar": "java",
            "tab_to_spaces": True,
        },
        "js": {
            "ext": [".json", ".js"],
            "grammar": "js",
            "tab_to_spaces": True,
        },
        "json5": {
            "ext": [".json5"],
            "grammar": "json5",
            "tab_to_spaces": True,
        },
        "make": {
            "ext": [],
            "grammar": "make",
            "name": ["Makefile"],
            "tab_to_spaces": False,
        },
        "md": {
            "ext": [".md"],
            "grammar": "md",
            "tab_to_spaces": True,
        },
        "proto": {
            "ext": [".proto"],
            "grammar": "proto",
            "tab_to_spaces": True,
        },
        "python": {
            "ext": [".py"],
            "grammar": "py",
            "tab_to_spaces": True,
        },
        "rust": {
            "ext": [".rs"],
            "grammar": "rs",
            "tab_to_spaces": True,
        },
        "text": {
            "ext": [".txt"],
            "grammar": "text",
            "tab_to_spaces": False,
        },
        "words": {
            "ext": [".words", ""],
            "grammar": "words",
            "tab_to_spaces": True,
        },
    },
    "grammar": {
        # A grammar is
        # "grammar_name": {
        #   "begin": None or regex,
        #   "continuation": None or string,
        #       Prefixed used when continuing to another line,
        #   "end": None or regex; a value of None means that the "begin" regex
        #       contains the entire pattern (a leaf grammar),
        #   "end_key": None or regex to determine dynamic end tag. For "here
        #       documents" and c++ string literals.
        #   "error": None or list of string.
        #   "escaped": None or regex,
        #   "indent": None or string,
        #   "next": other grammars that may follow this grammar without nesting
        #       within it. (Contrast with "contains").
        #   "numbers": None or list of string,
        #   "keywords": None or list of string. Matches whole words only (wraps
        #       values in \b).
        #   "single_line": Boolean, Whether entire grammar must be on a single
        #       line,
        #   "special": None or list of string.
        #   "tab_to_spaces": Boolean, Convert/expand tabs to spaces (see tab_size).
        #   "type": text or binary. default: text.
        #   "contains": other grammars that may be contained within this
        #       grammar.
        # }
        # The entries for "error", "keywords", and "special" are very similar.
        # Other than "keywords" being wrapped in \b markers, the difference
        # between them is just how they are drawn (color and style).
        "_pre": {
            "contains": ["_pre_selection"],
            "spelling": False,
        },
        "_pre_selection": {
            "begin": r"-->",
            "end": r"<--",
            "spelling": False,
        },
        # Bash shell.
        "bash": {
            "indent": "  ",
            "keywords": [
                "break",
                "case",
                "continue",
                "declare",
                "do",
                "done",
                "echo",
                "elif",
                "else",
                "esac",
                "exit",
                "fi",
                "if",
                "for",
                "return",
                "switch",
                "then",
                "while",
            ],
            # Not really types.
            "types": __linux_commands,
            "contains": ["c_string1", "c_string2", "pound_comment"],
        },
        # Bazel build script. See https://www.bazel.build/
        "bazel": {
            "indent": "  ",
            "keywords": ["testonly"],
            "types": "",
            "contains": ["py_string1", "py_string2", "pound_comment"],
        },
        "binary": {
            "spelling": False,
            "type": "binary",
        },
        # C language.
        "c": {
            "indent": "  ",
            "keywords": __c_keywords,
            "types": __c_primitive_types,
            "contains": [
                "cpp_block_comment",
                "cpp_line_comment",
                "c_preprocessor",
                "c_string1",
                "c_string2",
            ],
        },
        # C++ language.
        "cpp": {
            "indent": "  ",
            "keywords": __cpp_keywords,
            "namespaces": [
                "::",
                "std::",
            ],
            "types": __c_primitive_types
            + [
                "char8_t",
                "char16_t",
                "char32_t",
            ],
            "contains": [
                "cpp_block_comment",
                "cpp_line_comment",
                "c_preprocessor",
                "cpp_string_literal",
                "c_string1",
                "c_string2",
            ],
        },
        "cpp_block_comment": {
            "begin": r"/\*",
            "continuation": " * ",
            "end": r"\*/",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"\bNOTE:",
                _todo,
                __chrome_extension,
                __sha_1,
            ],
        },
        "cpp_line_comment": {
            "begin": "//",
            "continuation": "// ",
            "end": r"(?<!\\)\n",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"\bNOTE:",
                _todo,
                __chrome_extension,
                __sha_1,
            ],
        },
        "c_preprocessor": {
            "begin": r"^#",
            "end": r"(?<!\\)\n",
            "indent": "  ",
            "special": [
                r"\bdefine\b",
                r"\bdefined\b",
                r"\belif\b",
                r"\belif\b",
                r"\belse\b",
                r"\bendif\b",
                r"\bif\b",
                r"\bifdef\b",
                r"\bifndef\b",
                r"\binclude\b",
                r"\bpragma\b",
                r"\bundef\b",
            ],
            "next": [
                "c_preprocessor_include",
            ],
        },
        "c_preprocessor_include": {
            "begin": r"\binclude",
            "end": r"(?<!\\)\n",
            "contains": ["c_path_quoted_file", "c_path_bracketed_file"],
        },
        "c_raw_string1": {
            "begin": "[uU]?[rR]'",
            "end": "'",
            "escaped": r"\\'",
            "indent": "  ",
            "single_line": True,
            "special": __special_string_escapes + [r"\\'"],
        },
        "c_raw_string2": {
            "begin": '[uU]?[rR]"',
            "end": '"',
            "escaped": '\\\\"',
            "indent": "  ",
            "single_line": True,
            "special": __special_string_escapes + ['\\\\"'],
        },
        "cpp_string_literal": {
            "begin": 'R"',
            # TODO(dschuyler): backslash and whitespace are invalid in the
            # |end_key|.
            "end_key": """R\"([^(]*)\\(""",
            "end": '\\)\\0"',
            "single_line": False,
        },
        "c_string1": {
            "begin": "'(?!'')",
            "end": "'",
            "escaped": r"\\'",
            "indent": "  ",
            "special": __special_string_escapes + [r"\\'"],
            "single_line": True,
        },
        "c_string2": {
            "begin": '"(?!"")',
            "end": '"',
            "escaped": '\\\\"',
            "indent": "  ",
            "special": __special_string_escapes
            + [
                '\\\\"',
                r"%:#?-?[0-9]*\.?[0-9]*z?\w",
            ],
            "single_line": True,
        },
        "c_path_bracketed_file": {
            # Paths in includes don't allow escapes.
            "begin": """<[^>\\n]*>""",
            "end": None,  # Leaf grammar.
            "link_type": "c<",  # C system include file.
        },
        "c_path_quoted_file": {
            # Paths in includes don't allow escapes.
            "begin": '''"[^"\\n]*"''',
            "end": None,  # Leaf grammar.
            "link_type": 'c"',  # C non-system include file.
        },
        "carriage_return": {
            "begin": "\\n",
            "end": None,  # Leaf grammar.
        },
        # Cascading Style Sheet.
        "css": {
            "begin": "<style",
            "end": "</style>",
            "indent": "  ",
            "keywords": [
                "host",
                "slotted",
            ],
            "special": [r"#[\w-]+"],
            "contains": ["cpp_block_comment", "css_block"],
        },
        "css_block": {
            "begin": r"\\{",
            "end": r"\\}",
            "indent": "  ",
            "keywords": [
                "background-color",
                "color",
                "display",
                "font-family",
                "font-size",
                "height",
                "max-height",
                "min-height",
                "width",
                "max-width",
                "min-width",
            ],
            "special": [
                r"@apply\b",
            ],
            "contains": ["cpp_block_comment", "css_value"],
        },
        "css_value": {
            "begin": ":",
            "end": ";",
            "errors": [
                r"#(?:[^;]{1,2}|[^;]{5}|[^;]{7}|[^;]{9,})\b",
            ],
            "indent": "  ",
            "keywords": [
                "absolute",
                "attr",
                "block",
                "border-box",
                "calc",
                "center",
                "default",
                "ease",
                "hidden",
                "inherit",
                "left",
                "none",
                "px",
                "rgb",
                "rgba",
                "right",
                "rotate[XYZ]?",
                "scale[XYZ]?",
                "solid",
                "transform",
                "translate[XYZ]?",
                "transparent",
                "var",
            ],
            "special": [
                r"@apply\b",
                r"\d+deg\b",
                r"\d+em\b",
                r"\d+px\b",
                r"\d+rem\b",
                r"#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})",
            ],
            "contains": [
                "cpp_block_comment",
            ],
        },
        # Dart language.
        "dart": {
            "indent": "  ",
            "keywords": [
                "abstract",
                "as",
                "assert",
                "async",
                "async",
                "await",
                "break",
                "case",
                "catch",
                "class",
                "const",
                "continue",
                "covariant",
                "default",
                "deferred",
                "do",
                "dynamic",
                "else",
                "enum",
                "export",
                "extends",
                "external",
                "factory",
                "false",
                "final",
                "finally",
                "for",
                "get",
                "if",
                "implements",
                "import",
                "in",
                "interface",
                "is",
                "library",
                "mixin",
                "new",
                "null",
                "operator",
                "part",
                "rethrow",
                "return",
                "set",
                "static",
                "super",
                "switch",
                "sync",
                "this",
                "throw",
                "true",
                "try",
                "typedef",
                "var",
                "void",
                "while",
                "with",
                "yield",
            ],
            "types": [
                "bool",
                "Iterable",
                "String",
                "Map",
                "Int64",
                "Future",
                "int",
                "Timestamp",
            ],
            "special": [
                "@immutable",
                "@override",
                "@protected",
                "@required",
            ],
            "contains": [
                # This list is carefully ordered. Don"t sort it.
                "py_string1",
                "py_string2",
                "py_raw_string1",
                "py_raw_string2",
                "c_raw_string1",
                "c_raw_string2",
                "c_string1",
                "c_string2",
                "cpp_line_comment",
                "dart_nesting_block_comment",
            ],
        },
        "dart_nesting_block_comment": {
            "begin": r"/\*",
            "continuation": " * ",
            "end": r"\*/",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"\bNOTE:",
                _todo,
                __chrome_extension,
                __sha_1,
            ],
            "contains": [
                "dart_nesting_block_comment",
            ],
        },
        "doc_block_comment": {
            "begin": r"/\*\*",
            "continuation": " * ",
            "end": r"\*/",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"@param\b",
                r"@private\b",
                r"@protected\b",
                r"@type\b",
                r"@typedef\b",
                r"@return\b",
                r"\bNOTE:",
                _todo,
            ],
            "types": ["Array", "boolean", "string", "Object"],
        },
        "error": {
            "indent": "  ",
            "spelling": False,
        },
        "fidl": {
            "indent": "  ",
            "keywords": [
                "bits",
                "compose",
                "enum",
                "error",
                "library",
                "protocol",
                "struct",
                "table",
                "union",
                "using",
            ],
            "special": ["\[Discoverable\]"],
            "types": [
                "array",
                "handle",
                "int8",
                "int16",
                "int32",
                "int64",
                "string",
                "uint8",
                "uint16",
                "uint32",
                "uint64",
                "vector",
            ],
            "contains": [
                "cpp_line_comment",
                "c_string1",
                "c_string2",
            ],
        },
        # Generate Ninja language.
        "gn": {
            "indent": "  ",
            "keywords": ["else", "false", "foreach", "if", "import", "true"],
            "special": [],
            "types": [],
            "contains": [
                "pound_comment",
                "c_string1",
                "c_string2",
            ],
        },
        # Go Language.
        "golang": {
            "indent": "  ",
            "keywords": [
                "break",
                "case",
                "chan",
                "const",
                "continue",
                "default",
                "defer",
                "else",
                "fallthrough",
                "for",
                "func",
                "go",
                "goto",
                "if",
                "import",
                "interface",
                "map",
                "nil",
                "package",
                "range",
                "return",
                "select",
                "struct",
                "switch",
                "type",
                "var",
            ],
            "special": [
                # r"(?<!\w)__.*?__(?!\w)",
            ],
            "contains": [
                "cpp_block_comment",
                "cpp_line_comment",
                "cpp_string_literal",
                "c_string1",
                "c_string2",
            ],
        },
        "grd": {
            "keywords": ["flattenhtml", "allowexternalscript"],
        },
        "html": {
            "begin": "<html>",
            "end": app.regex.RE_NON_MATCHING,
            "errors": [
                "</br>",
                "</hr>",
                "</img>",
                "</input>",
            ],
            "indent": "  ",
            "keywords": [
                # "body", "button", "div", "head", "html", "href", "img",
                # "input", "script", "select", "span", "style",
            ],
            "special": [
                r"&.{1,5}?;",
                '<if\s+expr="[^"]*[^>]*>',
                "</if>",
            ],
            "contains": [
                "quoted_string1",
                "quoted_string2",
                "css",
                "html_block_comment",
                "js",
                "html_element",
                "html_element_end",
            ],
        },
        "html_block_comment": {
            "begin": "<!--",
            "end": "-->",
            "indent": "  ",
        },
        "html_element": {
            "begin": r"<[\w-]+",  # The "-" is used by Polymer.
            "contains": [
                "html_element_attribute",
            ],
            "end": ">",
            "special": [
                r"\\w+",
            ],
        },
        "html_element_attribute": {
            "begin": '\\??="',
            "end": '"',
        },
        "html_element_end": {
            "begin": r"</\\w+",
            "end": ">",
        },
        "java": {
            "indent": "  ",
            "keywords": __common_keywords
            + [
                "case",
                "class",
                "default",
                "do",
                "false",
                "interface",
                "switch",
                "this",
                "true",
            ],
            "contains": [
                "c_string1",
                "c_string2",
                "cpp_block_comment",
                "cpp_line_comment",
            ],
        },
        # JavaScript language.
        "js": {
            "begin": "<script",
            "end": "</script>",
            "indent": "  ",
            "keywords": [
                "arguments",
                "break",
                "case",
                "class",
                "const",
                "continue",
                "default",
                "delete",
                "document",
                "else",
                "false",
                "for",
                "function",
                "if",
                "instanceof",
                "let",
                "of",
                "return",
                "static",
                "switch",
                "super",
                "this",
                "true",
                "undefined",
                "var",
                "while",
                "yield",
            ],
            "special": [
                "\bsetTimeout\b",
                "\brequestCallback\b",
                "\bconsole\b",
                "\bwindow\b",
            ],
            "contains": [
                "c_string1",
                "c_string2",
                "doc_block_comment",
                "cpp_block_comment",
                "cpp_line_comment",
                "regex_string",
                "js_string",
            ],
        },
        "js_string": {
            "begin": r"`",
            "end": r"`",
            "escaped": r"\\`",
            "indent": "  ",
            "special": __special_string_escapes + [r"\\`", r"(?<!\\)\$\{[^}]*\}"],
            "single_line": False,
        },
        "keyword": {
            "indent": "  ",
            "spelling": False,
        },
        # JSON5 configuration data.
        "json5": {
            "indent": "  ",
            "keywords": [
            ],
            "special": [
                r"\w+:",
            ],
            "contains": [
                "c_string1",
                "c_string2",
                "doc_block_comment",
                "cpp_block_comment",
                "cpp_line_comment",
                "regex_string",
                "js_string",
            ],
        },
        # Makefile
        "make": {
            "indent": "\t",
            "keywords": [
                "ifeq",
                "endif",
                "ifneq",
                "break",
                "case",
                "continue",
                "do",
                "done",
                "echo",
                "else",
                "esac",
                "exit",
                "fi",
                "if",
                "for",
                "return",
                "switch",
                "then",
                "while",
            ],
            # Not really types.
            "types": __linux_commands,
            "contains": ["c_string1", "c_string2", "pound_comment"],
        },
        # Markdown language.
        "md": {
            "indent": "  ",
            "keywords": [],
            # "special": [ r"#.*" ],
            # "special": [r"\[[^]]+\]\([^)]+\)"],
            "contains": [
                "md_link",
                "md_code",
                "md_heading",
                # "quoted_string1", "quoted_string2"
            ],
        },
        "md_code": {
            "begin": "`",
            "end": "`",
            "indent": "  ",
        },
        "md_heading": {
            "begin": "^#",
            "continuation": "# ",
            "end": r"\n",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"\bNOTE:",
                _todo,
            ],
        },
        "md_link": {
            "begin": "\[",
            "end": "\]",
            "escaped": r"\\\]",
            "indent": "  ",
        },
        "none": {
            "spelling": False,
        },
        # Proto buffer language.
        "proto": {
            "indent": "  ",
            "keywords": __common_keywords
            + ["message", "option", "package", "returns", "rpc", "syntax"],
            "namespaces": [],
            "special": [
                # r"(?<!\w)__.*?__(?!\w)",
            ],
            "types": [
                "bool",
                "bytes",
                "double",
                "enum",
                "float",
                "int8",
                "int16",
                "int32",
                "int64",
                "optional",
                "repeated",
                "required",
                "string",
                "uint8",
                "uint16",
                "uint32",
                "uint64",
            ],
            "contains": [
                # This list is carefully ordered. Don"t sort it.
                "c_string1",
                "c_string2",
                "cpp_line_comment",
            ],
        },
        # Python language.
        "py": {
            "indent": "    ",
            "keywords": __common_keywords
            + [
                "and",
                "as",
                "assert",
                "class",
                "def",
                "del",
                "dict",
                "elif",
                "except",
                "False",
                "finally",
                "from",
                "global",
                "import",
                "in",
                "is",
                "len",
                "list",
                "None",
                "not",
                "or",
                "pass",
                "raise",
                "range",
                "self",
                "True",
                "try",
                "tuple",
                "until",
                "with",
                "yield",
            ],
            "namespaces": [
                "os\.",
                "os\.path\.",
                "sys\.",
                "traceback\.",
                "re\.",
            ],
            "special": [
                # r"(?<!\w)__.*?__(?!\w)",
            ],
            "types": [
                "Exception",
            ],
            "contains": [
                # This list is carefully ordered. Don"t sort it.
                "py_string1",
                "py_string2",
                "py_raw_string1",
                "py_raw_string2",
                "c_raw_string1",
                "c_raw_string2",
                "c_string1",
                "c_string2",
                "pound_comment",
                "py_from",
                "py_import",
            ],
        },
        "pound_comment": {
            "begin": "#",
            "continuation": "# ",
            "end": r"\n",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"\bNOTE:",
                _todo,
            ],
        },
        "py_from": {
            "begin": "from",
            "end": r"\n",
            "contains": ["py_import_file"],
            "next": ["py_import_after_from", "pound_comment"],
            "spelling": False,
        },
        "py_import_after_from": {
            "begin": "import",
            "end": None,
        },
        "py_import": {
            "begin": "import",
            "end": r"\n",
            "keywords": [
                "as",
            ],
            "contains": ["py_import_file"],
            "next": ["pound_comment"],
            "spelling": False,
        },
        "py_import_file": {
            "begin": "[\.\w]+",
            "end": None,  # Leaf grammar.
            "link_type": r"pi",  # Python import
            "spelling": False,
        },
        "py_raw_string1": {
            "begin": "[uU]?[rR]'''",
            "end": "'''",
            "escaped": r"\\'",
            "indent": "  ",
            # "special": ["\"\"?\"?$"],
        },
        "py_raw_string2": {
            "begin": '[uU]?[rR]"""',
            "end": '"""',
            "escaped": '\\\\"',
            "indent": "  ",
            # "special": ["\\\\\""],
        },
        "py_string1": {
            "begin": "[uU]?'''",
            "end": "'''",
            "escaped": r"\\'",
            # "indent": "  ",
            "single_line": False,
            "special": __special_string_escapes + [r"\\'"],
        },
        "py_string2": {
            "begin": '[uU]?"""',
            "end": '"""',
            "escaped": r'\\"',
            # "indent": "  ",
            "single_line": False,
            "special": __special_string_escapes + [r'\\"'],
        },
        "quoted_string1": {
            # This is not a programming string, there are no escape chars.
            "begin": "'",
            "end": "'",
        },
        "quoted_string2": {
            # This is not a programming string, there are no escape chars.
            "begin": '"',
            "end": '"',
        },
        "regex_string": {
            "begin": r"(?<=[\n=:;([{,])(?:\s*)/(?![/*])",
            "end": "/",
            "escaped": r"\\.",
            "indent": "  ",
            "special": __special_string_escapes + [r"\\/"],
            "single_line": True,
        },
        # Rust language.
        "rs": {
            "indent": "    ",
            "keywords": [
                "abstract",
                "alignof",
                "as",
                "async",
                "await",
                "become",
                "box",
                "break",
                "const",
                "continue",
                "crate",
                "do",
                "dyn",
                "else",
                "enum",
                "extern",
                "false",
                "final",
                "fn",
                "for",
                "if",
                "impl",
                "in",
                "let",
                "loop",
                "macro",
                "match",
                "mod",
                "move",
                "mut",
                "offsetof",
                "override",
                "priv",
                "pub",
                "pure",
                "ref",
                "return",
                "Self",
                "self",
                "sizeof",
                "static",
                "struct",
                "super",
                "trait",
                "true",
                "type",
                "typeof",
                "try",
                "unsafe",
                "unsized",
                "use",
                "virtual",
                "where",
                "while",
                "yield",
            ],
            "special": [
                "\\b\\w+!",
                "\\bNone\\b",
                "\\bOption\\b",
                "\\bResult\\b",
                "\\bSome\\b",
                "\\bunimplemented!",
            ],
            "types": [
                "bool",
                "char",
                "i8",
                "i16",
                "i32",
                "i64",
                "isize",
                "u8",
                "u16",
                "u32",
                "u64",
                "usize",
                "array",
                "slice",
                "tuple",
            ],
            "contains": [
                "rs_block_comment",
                "cpp_line_comment",
                # Using "rs_label_or_char" rather than "c_string1".
                "c_string2",
                "rs_byte_string1",
                "rs_byte_string2",
                "rs_label_or_char",
                "rs_raw_string",
            ],
        },
        # Rust block comments may be nested (unlike cpp_block_comments).
        "rs_block_comment": {
            "begin": r"/\*",
            "continuation": " * ",
            "end": r"\*/",
            "indent": "  ",
            "keywords": [],
            "special": [
                r"\bNOTE:",
                _todo,
                __chrome_extension,
                __sha_1,
            ],
            "contains": [
                "rs_block_comment",
            ],
        },
        "rs_byte_string1": {
            "begin": "b'",
            "end": "'",
        },
        "rs_byte_string2": {
            "begin": 'b"',
            "end": '"',
        },
        # Rust uses ' for both the start of a label and the start of a character
        # literal.
        "rs_label_or_char": {
            "begin": "'\\w*'?",
            "end": None,
            "single_line": True,
        },
        # Rust uses ' for both the start of a label and the start of a character
        # literal.
        "rs_label_or_char": {
            "begin": "'\\w*'?",
            "end": None,
            "single_line": True,
        },
        "rs_raw_string": {
            "begin": 'b?r#*"',
            # TODO(dschuyler): backslash and whitespace are invalid in the
            # |end_key|.
            "end_key": """b?r(#*)\"""",
            "end": '"\\0',
            "single_line": False,
        },
        "special": {
            "indent": "  ",
            "spelling": False,
        },
        "tabs": {
            "indent": "",
            "spelling": False,
        },
        "text": {
            "special": [
                __sha_1,
            ],
            "contains": ["quoted_string1", "quoted_string2"],
        },
        "type": {
            "indent": "  ",
            "spelling": False,
        },
        # Dictionary file for ci_edit.
        "words": {
            "contains": [
                "pound_comment",
            ],
        },
    },
    "palette": {
        # Note: index 0 of each palette is not set, it remains as the system
        # entry.
        "test": {
            # Same foreground color in all 256 slots.
            "foreground_indexes": [18] * 256,
            # Separate background color in every slot.
            "background_indexes": [i for i in range(0, 256)],
        },
        "dark": {
            # This series repeats 8 times (32 * 8 = 256).
            "foreground_indexes": [
                14,
                202,
                39,
                39,
                39,
                39,
                39,
                39,
                39,
                39,
                39,
                39,
                12,
                13,
                14,
                15,
                202,
                14,
                14,
                202,
                202,
                202,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                57,
            ]
            * 8,
            # Each of the foreground colors repeat 8 times (32 * 8 = 256).
            "background_indexes": [232] * 32
            + [229] * 32
            + [6] * 32
            + [221] * 32
            + [245] * 32
            + [244] * 32
            + [243] * 32
            + [225] * 32,
        },
        "default8": {
            # With only 8 colors, make a custom pair for each slot.
            # 0: black, 1: red, 2: green, 3: yellow, 4: blue, 5: pink, 6: cyan,
            # 7: gray.
            "foreground_indexes": [1, 4, 2, 3, 4, 5, 6, 0],
            "background_indexes": [0, 6, 7, 7, 7, 7, 7, 7],
        },
        "default16": {
            # With only 16 colors, make a custom pair for each slot.
            # 0: black, 1: red, 2: green, 3: yellow, 4: blue, 5: pink, 6: cyan,
            # 7: gray.
            "foreground_indexes": [0, 1, 2, 3, 4, 5, 6, 7, 8, 4, 2, 3, 4, 5, 6, 0],
            "background_indexes": [
                0,
                15,
                15,
                15,
                15,
                15,
                15,
                15,
                7,
                7,
                7,
                7,
                7,
                7,
                7,
                15,
            ],
        },
        "default256": {
            # This series repeats 8 times (32 * 8 = 256).
            "foreground_indexes": [
                18,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                94,
                134,
                0,
                240,
                138,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                57,
            ]
            * 8,
            # Each of the foreground colors repeat 8 times (32 * 8 = 256).
            "background_indexes": [231] * 32
            + [229] * 32
            + [14] * 32
            + [221] * 32
            + [255] * 32
            + [254] * 32
            + [253] * 32
            + [225] * 32,
        },
    },
    "status": {
        "show_tips": False,
    },
    "user_data": {
        "home_path": os.path.expanduser("~/.ci_edit"),
        "history_path": os.path.join(os.path.expanduser("~/.ci_edit"), "history.dat"),
    },
}

# Alias for old palette name.
prefs["palette"]["default"] = prefs["palette"]["default256"]
